version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: cypress/base:12.6.0
    steps:
      - checkout
      - cypress/install
      - run:
          name: Run Tests
          command: |
            npm test
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos
